dist: precise
language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
script:
  - ./gradlew test
after_success:
  - ./gradlew jacocoTestReport coveralls
addons:
  hosts:
    - example.com
  hostname: example.com
